plugins {
    id("com.android.application")
    id("kotlin-android")
    id("kotlin-android-extensions")
}

android {
    compileSdkVersion(Deps.compileSdk)
    buildToolsVersion(Deps.buildTools)
    defaultConfig {
        applicationId = "com.samelody.samples.dep"
        minSdkVersion(Deps.minSdk)
        targetSdkVersion(Deps.targetSdk)
        versionCode = 1
        versionName = "1.0"
        testInstrumentationRunner = "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro")
        }
    }
}

dependencies {
    implementation(fileTree(mapOf("dir" to "libs", "include" to listOf("*.jar"))))
    implementation(Deps.kotlinStdlib)
    implementation(Deps.kotlinStdlibJdk8)
    implementation(Deps.kotlinReflect)
//    implementation(Deps.kotlinCompiler)
    implementation(Deps.adsId)
    implementation(Deps.adsIdProvider)
    implementation(Deps.annotation)
    implementation(Deps.annotationExperimental)
    implementation(Deps.core)
    implementation(Deps.coreRole)
    implementation(Deps.coreAnimation)
    implementation(Deps.cameraCore)
    implementation(Deps.cameraCamera2)
    implementation(Deps.cameraView)
    implementation(Deps.cameraExtensions)
    implementation(Deps.cameraLifecycle)
    implementation(Deps.customView)
    implementation(Deps.activity)
    implementation(Deps.biometric)
    implementation(Deps.browser)
    implementation(Deps.dataBinding)
    implementation(Deps.dataBindingAdapters)
    implementation(Deps.dynamicAnimation)
    implementation(Deps.flexbox)
    implementation(Deps.enterpriseFeedback)
    implementation(Deps.fragment)
    implementation(Deps.fragmentTesting)
    implementation(Deps.loader)
    implementation(Deps.futures)
    implementation(Deps.listenableFuture)
    implementation(Deps.listenableFutureCallback)
    implementation(Deps.preference)
    implementation(Deps.viewModel)
    implementation(Deps.viewModelSavedState)
    implementation(Deps.liveData)
    implementation(Deps.recyclerView)
    implementation(Deps.recyclerViewSelection)
    implementation(Deps.lifecycle)
    implementation(Deps.lifecycleProcess)
    implementation(Deps.lifecycleService)
    implementation(Deps.lifecycleJava8)
    implementation(Deps.lifecycleReactiveStreams)
    implementation(Deps.appCompat)
    implementation(Deps.appCompatResources)
    implementation(Deps.autofill)
    implementation(Deps.emoji)
    implementation(Deps.emojiAppCompat)
    implementation(Deps.emojiBundled)
    implementation(Deps.room)
    implementation(Deps.roomMigration)
    implementation(Deps.sqlite)
    implementation(Deps.shareTarget)
    implementation(Deps.securityCrypto)
    implementation(Deps.versionedParcelable)
    implementation(Deps.paging)
    implementation(Deps.pagingRxJava)
    implementation(Deps.heifWriter)
    implementation(Deps.palette)
    implementation(Deps.recommendation)
    implementation(Deps.material)
    implementation(Deps.coroutinesCore)
    implementation(Deps.coroutinesAndroid)
    implementation(Deps.kotlinIo)
    implementation(Deps.atomicfu)
    implementation(Deps.media)
    implementation(Deps.mediaWidget)
    implementation(Deps.media2Common)
    implementation(Deps.media2Widget)
    implementation(Deps.media2Session)
    implementation(Deps.media2Player)
    implementation(Deps.media2ExoPlayer)
    implementation(Deps.mediaRouter)
    implementation(Deps.exifInterface)
    implementation(Deps.contentPager)
    implementation(Deps.slice)
    implementation(Deps.sliceView)
    implementation(Deps.sliceBuilders)
    implementation(Deps.multiDex)
    implementation(Deps.savedState)
    implementation(Deps.navigation)
    implementation(Deps.navigationUi)
    implementation(Deps.navigationFragment)
    implementation(Deps.collection)
    implementation(Deps.constraintLayout)
    implementation(Deps.swipeRefreshLayout)
    implementation(Deps.slidingPaneLayout)
    implementation(Deps.drawerLayout)
    implementation(Deps.gridLayout)
    implementation(Deps.cardView)
    implementation(Deps.transition)
    implementation(Deps.textClassifier)
    implementation(Deps.viewPager)
    implementation(Deps.viewPager2)
    implementation(Deps.biometric)
    implementation(Deps.car)
    implementation(Deps.wear)
    implementation(Deps.work)
    implementation(Deps.workRxJava)
    implementation(Deps.webkit)
    implementation(Deps.leanback)
    implementation(Deps.leanbackPreference)
    implementation(Deps.localBroadcastManager)
    implementation(Deps.tvProvider)
    implementation(Deps.vectorDrawable)
    implementation(Deps.vectorDrawableAnimated)
    implementation(Deps.vectorDrawableSeekable)
    implementation(Deps.interpolator)
    implementation(Deps.ktorClientCore)
    implementation(Deps.ktorClientCoreJvm)
    implementation(Deps.ktorClientAndroid)
    implementation(Deps.ktorClientOkHttp)
    implementation(Deps.ktorClientJson)
    implementation(Deps.ktorClientGson)
    implementation(Deps.okhttp)
    implementation(Deps.okio)
    implementation(Deps.arrowCore)
    implementation(Deps.glide)
    implementation(Deps.rxJava)
    implementation(Deps.photoView)
    implementation(Deps.exoPlayer)
    implementation(Deps.exoPlayerRtmp)
    implementation(Deps.retrofit)
    implementation(Deps.gson)
    implementation(Deps.coordinatorLayout)
    implementation(Deps.zxing)
    implementation(Deps.simpleCropView)
    implementation(Deps.remoteCallback)
    implementation(Deps.eventBus)
    implementation(Deps.gifEncoder)
    implementation(Deps.arCore)
//    implementation(Deps.wcdb)
    implementation(Deps.mmkv)
//    implementation(Deps.halCore)
//    implementation(Deps.halCoreLiveData)
//    implementation(Deps.sceneformCore)
//    implementation(Deps.sceneformUx)
//    implementation(Deps.eiffel)
    implementation(Deps.easyPermissions)
    implementation(Deps.leakCanary)
    implementation(Deps.lottie)
    implementation(Deps.mvrx)
    implementation(Deps.subsamplingImageView)
    implementation(Deps.fresco)
    implementation(Deps.frescoAnimated)
    implementation(Deps.frescoGif)
    implementation(Deps.frescoWebp)
//    implementation(Deps.workflowAndroid)
    implementation(Deps.coil)
    implementation(Deps.coilGif)
//    implementation(Deps.kotlinImmutableCollections)
    implementation(Deps.timber)
    implementation(Deps.imageViewTouch)
//    implementation(Deps.hawk)
//    implementation(Deps.guava)
    implementation(Deps.window)
    implementation(Deps.windowExtensions)
    implementation(Deps.materialDialogsCore)
    implementation(Deps.materialDialogsDateTime)
    implementation(Deps.qmui)
    implementation(Deps.qmuiArch)
    implementation(Deps.materialDrawer)
    implementation(Deps.spyglass)
    implementation(Deps.liTr)
    implementation(Deps.tachyon)
    implementation(Deps.jsonCpp)

    testImplementation(Deps.benchmark)
    testImplementation(Deps.workTesting)
    testImplementation(Deps.testCore)
    testImplementation(Deps.testMonitor)
    testImplementation(Deps.testRunner)
    testImplementation(Deps.testRules)
    testImplementation(Deps.espresso)
    testImplementation(Deps.junit)
    testImplementation(Deps.coroutinesTest)
    testImplementation(Deps.coroutinesDebug)
}
